### ISSUE TITLE
Non-RFC compliant HTTP error responses

### ISSUE THREAD

**Issue by Kagami** [kanaka/websockify#106]
When using websockify in the `file_only=True` mode the server doesn't send CRLF indicating the end of the header fields.

RFC 2616 requires that each HTTP message contain CRLF after the headers. See:
* http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html (section 4.1)
* http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html (section 6)

Simple example demonstrating the problem:
```python
import websockify
server = websockify.WebSocketProxy(
    listen_host='127.0.0.1', listen_port='22333',
    web='test', file_only=True)
server.start_server()
```

```shell
$ curl --silent --include http://127.0.0.1:22333/not-existent
HTTP/1.0 404 No such file
Server: SimpleHTTP/0.6 Python/2.7.5
Date: Thu, 14 Nov 2013 18:00:07 GMT
$ curl --silent --include http://127.0.0.1:22333/not-existent | hexdump -C
00000000  48 54 54 50 2f 31 2e 30  20 34 30 34 20 4e 6f 20  |HTTP/1.0 404 No |
00000010  73 75 63 68 20 66 69 6c  65 0d 0a 53 65 72 76 65  |such file..Serve|
00000020  72 3a 20 53 69 6d 70 6c  65 48 54 54 50 2f 30 2e  |r: SimpleHTTP/0.|
00000030  36 20 50 79 74 68 6f 6e  2f 32 2e 37 2e 35 0d 0a  |6 Python/2.7.5..|
00000040  44 61 74 65 3a 20 54 68  75 2c 20 31 34 20 4e 6f  |Date: Thu, 14 No|
00000050  76 20 32 30 31 33 20 31  38 3a 30 30 3a 33 39 20  |v 2013 18:00:39 |
00000060  47 4d 54 0d 0a                                    |GMT..|
00000065
```

Seems like the code in websocket.py is the reason of this behaviour:
https://github.com/kanaka/websockify/blob/master/websockify/websocket.py#L965
```python
        elif self.file_only and not os.path.isfile(abspath):
            self.send_response(404, "No such file")
        elif self.no_parent and not abspath.startswith(self.webroot):
            self.send_response(403, "Hidden resources")
```
(same issue for 403 error).
If I put `self.end_headers()` after the `self.send_response` everything work fine.

While this problem might look like minor issue (after all, curl(1) and browsers work just fine with such HTTP servers), it could have serious consequences. For example, nginx could not proxy such responses, answer with 502 instead of 404 and put this in error log:
```
[error] 28079#0: *271 upstream prematurely closed connection while reading response header from upstream
```
So please fix it.

**Comment by DirectXMan12** [comment]
This was fixed a while ago.
