### ISSUE TITLE
SSL doesn't work

### ISSUE THREAD

**Issue by burner1024** [kanaka/websockify#112]
Not sure if that's related to Websockify or noVNC. I've installed Websockify and generated the certificate, but the client won't connect over SSL (plain connection works fine). This is what I see in console:

```
xx.xx.xx.xx: new handler Process
  2: xx.xx.xx.xx: _ssl.c:480: EOF occurred in violation of protocol
Reaing zombies, active child count is 0
```

However, connecting with "openssl s_client -connect " doesn't complain about SSL at all.

**Comment by beeelze** [comment]
I'm still having problems with SSL and websockify. I raised this question on stackoverflow as well.

The error posted above occurs when connecting to websockify with SSL on Safari.

On FireFox I see: handler exception: [Errno 1] _ssl.c:1429: error:14094412:SSL 
                routines:SSL3_READ_BYTES:sslv3 alert bad certificate

On Chrome I see: handler exception: WSRequestHandler instance has no attribute 
                'last_code'

**Comment by jamielsharief** [comment]
I am also getting this issue, this only started to happen once I used the ubuntu minimal image vs the normal ubuntu server image, so I am pretty sure something is missing.
