### ISSUE TITLE
"file_only and no_parent" issue again in websockify 0.6.0?

### ISSUE THREAD

**Issue by darren-wang** [kanaka/websockify#136]
I was installing DevStack when I found this issue.

My env is ubuntu 14.04.1 Desktop with icehouse DevStack( and Nova) and websockify 0.6.0. Then this problem arose, I reported this issue to devstack as follow:

https://bugs.launchpad.net/devstack/+bug/1361108

Then I followed other's comment to find this was an old bug and was fixed in websockify 0.5.1 already:

https://bugs.launchpad.net/ubuntu/+source/nova/+bug/1228490

I tried to change nova/requirements.txt with "websockify >=0.5.1,<=0.6" instead of "websockify >=0.5.1,<0.6" but it didn't work.

Then I uninstalled websockify 0.6.0 and reinstalled websockify 0.5.1, the problem just fixed!

Because the pip automatically install the newest version of packages, could you fix this issue in websockify 0.6.0?

**Comment by DirectXMan12** [comment]
This should be modified in Nova.  noVNC v0.6.0 no longer uses the `no_parent` option (it's not needed -- Python's SimpleHTTPServer only serves content from the target directory anyway).
