### ISSUE TITLE
websockify does not react to SIGTERM

### ISSUE THREAD

**Issue by hamiltont** [kanaka/websockify#138]
Running websockify as normal (e.g. `websockify 6080 127.0.0.1:5900`), and then sending a SIGTERM to the process (e.g. `kill <websockify-pid>`) does nothing if there is a client connected. I would expect it to disconnect any clients and terminate itself. Instead, I seem to have to `kill -9 <websockify-master-pid>` to get this behavior 

If you SIGTERM the child process, it will kill that one client and the master will continue running, but this part is expected behavior as far as I am concerned

**Comment by abhishekkekane** [comment]
Hi,

Is anyone working on this issue, else I would like to take this up.

Abhishek

**Comment by DirectXMan12** [comment]
@abhishekkekane are you still experiencing the issue?  If so, we'd be glad to have a patch which fixes it.

**Comment by abhishekkekane** [comment]
Hi DirectXMan12,

Yes, issue is still there. I have checked with multiprocessing, and if I add below code after line [1] to kill the child processes then it works as per expectation.

```
except (self.Terminate, SystemExit, KeyboardInterrupt):
    self.msg("In exit")
+   # terminate all chiild processes
+   if multiprocessing and not self.run_once:
+       childs = multiprocessing.active_children()
+
+       for child in childs:
+           pid = child.pid
+           if pid != os.getpid():
+               self.msg("Terminating child %s" % pid)
+               os.kill(pid, signal.SIGTERM)
+
break
```

Should I push this patch?

[1] https://github.com/kanaka/websockify/blob/master/websockify/websocket.py#L108

**Comment by DirectXMan12** [comment]
Yes, please submit a pull request and mention this issue in the commit message (for example `Fixes #138`).

However, since we're using multiprocessing, you should be able to call `Process#terminate` instead of manually calling `kill` (see https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process.terminate)

**Comment by abhishekkekane** [comment]
Hi DirectXMan12,

I have submitted a pull request for addressing multiprocessing issue.

To resolve this issue if multiprocessing is disabled then psutil moduls needs to be used to get all active children of a given process. Please refer below code which will fix this issue for both, multiprocessing is supported or multiprocessing is not supported.

```
+ import psutil

except (self.Terminate, SystemExit, KeyboardInterrupt):
    self.msg("In exit")
+   # terminate all child processes
+   if not self.run_once:
+       childs = None
+       if multiprocessing:
+           childs = multiprocessing.active_children()
+       else:
+           try:
+               p = psutil.Process(os.getpid())
+           except psutil.NoSuchProcess:
+               return
+           childs = p.get_children(recursive=True)
+
+       for child in childs:
+           pid = child.pid
+           self.msg("Terminating child %s" % pid)
+           child.terminate()
+
break
```

**Comment by abhishekkekane** [comment]
Hi All,

Could you please review the patch submitted for this bug.
https://github.com/kanaka/websockify/pull/226

Also please let me know your opinion for comment https://github.com/kanaka/websockify/issues/138#issuecomment-179692646

Thank you.
