### ISSUE TITLE
Websocket frame corruption on big-endian

### ISSUE THREAD

**Issue by NiallPower** [kanaka/websockify#150]
I was try to connect to a VNC server using noVNC + Websockify on a SPARC system running Solaris. I noticed that X86 worked fine but the VNC session got terminated during handshake on SPARC. Further examination and on running the echo unit tests 'echo' and 'plain echo' revealed a possible byte order issue. I traced the issue down to the use of numpy to  apply the mask on the  data in the Websocket frame, which seems to assume that both will be in little-endian representation, which leads to a no-op on X86, but causes an invalid byte swap on big-endian ISAs like SPARC, some ARM , etc.

A very simple patch that resolved the problem for me is below.

Thanks,
Niall

--- websockify-0.5.1/websockify/websocket.py.orig       2015-01-13 14:59:26.3828
30765 -0700
+++ websockify-0.5.1/websockify/websocket.py    2015-01-13 14:58:26.088075181 -0
700
@@ -241,9 +241,9 @@
         if numpy:
             b = c = s2b('')
             if plen >= 4:
-                mask = numpy.frombuffer(buf, dtype=numpy.dtype('<u4'),
+                mask = numpy.frombuffer(buf, dtype=numpy.dtype('u4'),
                         offset=hlen, count=1)
-                data = numpy.frombuffer(buf, dtype=numpy.dtype('<u4'),
+                data = numpy.frombuffer(buf, dtype=numpy.dtype('u4'),
                         offset=pstart, count=int(plen / 4))
                 #b = numpy.bitwise_xor(data, mask).data
                 b = numpy.bitwise_xor(data, mask).tostring()

**Comment by DirectXMan12** [comment]
Good catch.  Can you submit a pull request for this?  That's how we normally accept patches.
