### ISSUE TITLE
rebind.so not found on CentOS 5.11 

### ISSUE THREAD

**Issue by FryShadow** [kanaka/websockify#151]
I've compiled and install from 

python2.7 setup.py install

The installation is success and websockify installed at /usr/local/bin/websockify. Is there any that I missed during the installation that produce rebind.so not found ?

Thanks

**Comment by DirectXMan12** [comment]
to get rebind.so, you need to run the Makefile (which builds rebind.so from rebind.c).  Note that rebind.so is really only needed if you're using websockify with the "wrap command" usage.
