### ISSUE TITLE
Interrupted system call

### ISSUE THREAD

**Issue by bkanuka** [kanaka/websockify#166]
This is a bit of a cross-post because I'm not entirely sure where this bug lives.  [WebVirtMgr](https://github.com/retspen/webvirtmgr) uses websockify somewhat unsuccessfully. See [this bug](https://github.com/retspen/webvirtmgr/issues/503).

The actual exception however, is happening in [websocketproxy.py line 134](https://github.com/kanaka/websockify/blob/master/websockify/websocketproxy.py#L134). `ins, outs, excepts = select(rlist, wlist, [], 1)` is throwing a `select.error error: (4, 'Interrupted system call')`

If the `select` timeout is set to 0, things work but obviously at high CPU.

The bug linked above may actually be the fault of WebVirtMgr, but ideally websockify should be robust to whatever WebVirtMgr is doing.

**Comment by bkanuka** [comment]
A reasonable reaction to an "Interrupted system call" is to try again. My patch just catches and continues (a little trickery to catch *just* "Interrupted system call")

**Comment by haypo** [comment]
> A reasonable reaction to an "Interrupted system call" is to try again.

Yes. For select.select(), you may need to recompute the timeout. But in do_proxy() calls select() in a "while True" loop, so I'm not sure that the timeout matters. By the way, why select() is called with a timeout? It looks like active polling, whereas it should work without polling.

See also the PEP 475 which restarts interrupted syscalls in Python 3.5:
https://www.python.org/dev/peps/pep-0475/

**Comment by bkanuka** [comment]
`select` is called with a timeout so that it blocks for *up to* one second. Without it, `select` never blocks and the encasing `while True` spins as fast as it can. I think the net effect is that the timeout doesn't really matter (as long as it's not 0).

Re: Python 3.x - it's the reason my patch wasn't merged. I'm not too familiar with Python 3 and especially not with code that's cross-compatible. Will have to look into this (fingers crossed for today).

Thank you for looking at this.

**Comment by psych0d0g** [comment]
@bkanuka after i've applied this patch, WebVirtMgr isnt connecting to spice at all anymore, without it connects but disconnects after few seconds like the initial issue, something seems not quite right here i guess

**Comment by bkanuka** [comment]
Whoa super good to know. Thanks! I'll look into it. Sorry this has totally
slipped away from me.
