### ISSUE TITLE
Ping and Pong Heartbeats

### ISSUE THREAD

**Issue by AricStewart** [kanaka/websockify#170]
Sorry, I am doing this backwards.

We have a need for websockify to work through a firewall that closes idle connection after a given very short number of seconds. The Websocket protocol has ping and pong messages defined to handle situations just like this.

I have submitted patches to websockify to implement these control messages to help with timeout issues such as this.

**Comment by DirectXMan12** [comment]
In the future, please mention the bug number in the PR or vice versa. 
For posterity: see #169

**Comment by AricStewart** [comment]
Understood, thanks for linking them up.

**Comment by DirectXMan12** [comment]
Closed by commit 452d9582cc82d640662cebbc1c573c4b1dbeb6b2
