### ISSUE TITLE
How to skip base64

### ISSUE THREAD

**Issue by lulingar** [kanaka/websockify#173]
I have read the codebase for the server and the proxy, and while `WebSocketRequestHandler` class and the server support raw binary frames, the proxy server makes no use of them, which makes all traffic to be b64 encoded. Is there any reason for this design other than browser backwards compatibility? 

I don't have much free time, but if the following observations hold, I can give a shot at enabling proxying b64-free (Only Python though, don't have much experience with the other languages):
* For the Python proxy server: Setting the `binary=True` flag in the `sent = target.send(dat)` line in the `do_proxy` function of the `ProxyRequestHandler` class would be all that's needed to avoid the server base64 encode the traffic.
* For the JavaScript client: Adding `"binary"` to the `protocols` argument of the `Websock.open` method would make the client ready for the binary frames emitted by the Python server.

**Comment by DirectXMan12** [comment]
I am unclear as to what issue you have.  Binary frames are definitely supported and used.

> Setting the binary=True flag in the sent = target.send(dat) line in the do_proxy function of the ProxyRequestHandler class would be all that's needed to avoid the server base64 encode the traffic.

the `target` socket, as the comment a few lines above indicates, is a normal TCP socket to the target server (which is a server which does not support websockets).
