### ISSUE TITLE
handler exception: WSRequestHandler instance has no attribute 'last_code'

### ISSUE THREAD

**Issue by chrism2671** [kanaka/websockify#183]
Anybody know what this means? This happens when trying to connect via WSS to websockify (used with noVNC). I'm using the websockify from the Ubuntu 14.04 LTS repository.

I generated the certificate as per the instructions on the the websockify readme.

Any pointers would be very helpful!

Thanks!
Chris.

**Comment by chrism2671** [comment]
I believe this issue is related to the self-signed certificate. Closing for now.

**Comment by ik-j** [comment]
I am getting this issue with commercial certificates. Can you anyone help out ?
