### ISSUE TITLE
Support POST method of built in web server

### ISSUE THREAD

**Issue by joshiggins** [kanaka/websockify#188]
Hi
we would like to support the POST method of the built in web server - we have a form that posts connection info to another page that initiates the websocket and it would be nice not to leak the parameters into the address bar.

What do you think?

**Comment by tg123** [comment]
I think it is impossible.
browser will start with a `GET` in websocket handshake. see <https://tools.ietf.org/html/rfc6455>.

however,
websocket supports cookie, you can `POST` something and then let browser request with cookie.

**Comment by joshiggins** [comment]
Apologies, I must not have described so well.

I mean not to upgrade a connection to a websocket from a `POST` request, just for the built in webserver to support the `POST` method when serving the static pages - it would be useful when testing an application that has for example, a form, like in the one I described above.

I tried this here https://github.com/joshiggins/websockify/commit/eb314a600185324dbbb6ec130f94d85fbac22cbd but it doesn't correctly pass the request parameters, probably because of use of the `SimpleHTTPRequestHandler.do_GET` method.

**Comment by DirectXMan12** [comment]
While it should theoretically be possible to support this (you'd probably have to write the POST method from scratch though -- check out the source of SimpleHTTPRequestHandler), in this case I'd probably recommend hosting the noVNC files, etc in their own webserver that's designed for that kind of thing, and then just using websockify without it's file-serving capabilities (which are convenient to use with vanilla noVNC, but aren't really designed for more complicated scenarios).
