### ISSUE TITLE
Daemonize do not seem to work

### ISSUE THREAD

**Issue by cotardp** [kanaka/websockify#189]
I am developing a python program and I need to use your websockify package.
However, I have an issue and I'd like to know your point.

I installed websockify from pypi to be able to use it inside my python program (v 0.7.0)
I'm running python 3.4 on ubuntu 14.04 LTS

I can use webosckify to act as a proxy as expected : (nb. 'gs' is an alias to a server running a service on port 13415)
```
$ websockify 5555 gs:13415 -v
WebSocket server settings:
  - Listen on :5555
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - proxying from :5555 to gs:13415
```
And I can connect to port 5555 from a custom wstelnet.html page.

But then I want to daemonize it :
```
$ websockify 5555 gs:13415 -v -D
WebSocket server settings:
  - Listen on :5555
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
$
```
And I cannot connect with the html page.

The socket seems to be existent, but no way to connect to it !
```
$ lsof |grep 5555
websockif 18719              pco    4u     IPv4             292245       0t0      TCP *:5555 (LISTEN)
```

The error from javascript console (chromium) is :
WebSocket connection to 'ws://XXXXX:5555/' failed: Error during WebSocket handshake: Invalid status line

I then tried to run it inside my program by importing the package. It works with daemon set to False.
But if set daemon to True, I have the same behaviour as above.
I also tried to run the server in a thread but it does not seem to be possible :
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "XXX", line 85, in serve_websocket
    server.start_server()
  File "/usr/local/lib/python3.4/dist-packages/websockify/websocket.py", line 954, in start_server
    signal.signal(signal.SIGINT, self.do_SIGINT)
ValueError: signal only works in main thread
```

So I cannot run it as a daemon, neither from command line, nor from python program.
Do you have an idea why I encounter this issue and how to fix it?

**Comment by DirectXMan12** [comment]
Sorry for the delayed response.  I am unable to reproduce your issue.

However, if you want to run websockify as a long-running service, I'd recommend using your OS's init system (OpenRC, systemd, Upstart, plain SysV, etc) to run noVNC as a service.  The daemonize option is useful for when you don't have that, but your init system is better suited to the task.
