### ISSUE TITLE
New npm release

### ISSUE THREAD

**Issue by timkurvers** [kanaka/websockify#199]
Is anyone aware of whether version `0.7.0` is available through npm? If it isn't, would it be possible to have a new release for the JavaScript version of websockify?

Thanks! :smile:

**Comment by DirectXMan12** [comment]
It's not at the moment (although, to be frank, there's not much that has changed).  I'll push an update later this week.  Sorry about that!

**Comment by timkurvers** [comment]
#185 is required to install on Node v0.12+, but definitely no rush. Thanks in advance!

**Comment by DirectXMan12** [comment]
Ah, that would actually be a v0.7.x release -- it was after the v0.7.0 tag.  I'll probably push it as v0.7.1 (just to keep the Python and Node versions vaguely in sync).

**Comment by DirectXMan12** [comment]
v0.7.1 should be up on NPM.
