### ISSUE TITLE
multiple targets apply

### ISSUE THREAD

**Issue by drt0927** [kanaka/websockify#200]
I tried to run cmd in the windows of a report from the target_list https://github.com/kanaka/websockify/issues/3.

websockify --web ./: 6080 192.168.2.119:5900 192.168.2.120:5900 192.168.2.121:5900

But

websockify [options] [source_addr:] source_port target_addr: target_port
websockify [options] [source_addr:] source_port - WRAP_COMMAND_LINE

It just came out this sentence .

and

target_list.cfg ==> {"target_list": ["192.168.2.119:5900", "192.168.2.120:5900", "192.168.2.142:5900"]}

websockify.exe --web="c:\users\desktop\Websockify Windows Service" target_list.cfg :6080

websockify [options] [source_addr:] source_port target_addr: target_port
websockify [options] [source_addr:] source_port - WRAP_COMMAND_LINE

websockify.exe: error: Error parsing listen port

It just came out this sentence .

also 

websockify.exe --web="c:\users\desktop\Websockify Windows Service" --target-list target_list.cfg :6080

websockify [options] [source_addr:] source_port target_addr: target_port
websockify [options] [source_addr:] source_port - WRAP_COMMAND_LINE

websockify.exe: error: no such option: --target-list

It just came out this sentence .

How do I apply target_list?

and How clients access the server?

host&port ex) vnc_auto.html?host=192.168.2.119&port=6080

target ex) vnc_auto.html?host=192.168.2.119&port=6080=target=host1   <<<This way?

**Comment by kanaka** [comment]
You can't pass multiple target on the command line like that. However, you can do it via configuration files: https://github.com/kanaka/websockify/wiki/Token-based-target-selection

**Comment by CodingYiyi** [comment]
how can we do this in windows sys? I noticed that https://github.com/kanaka/websockify/wiki/Token-based-target-selection
is a Linux solution, not windows.
am i right?

**Comment by CodingYiyi** [comment]
@kanaka is there a windows solution?

**Comment by kanaka** [comment]
@CodingYiyi I don't think there is anything in the token plugin code that is Linux specific. However, we don't officially support the python version of websockify on Windows (separate issues from the token code). The node version of websockify is known to work on Windows, however, it doesn't have the token based authentication merged yet. There is a pull request at https://github.com/novnc/websockify/pull/285 and you're welcome to try merging it yourself and testing it. If you get it working, be sure to give feedback on that PR since that would be helpful in deciding whether to merge it.

**Comment by CodingYiyi** [comment]
@kanaka thanks for your reply,It saves my time. I will try to do it.

**Comment by ik-j** [comment]
My questions seems a bit out of context but I have a situation where I need help. I want to run tightVNC single instance to listen on multiple ports and I am using noVNC using websockify (node version).

TightVNC does allow extra port option but websockify only listens at port 27016.
