### ISSUE TITLE
Enable logging file 

### ISSUE THREAD

**Issue by dwang2** [kanaka/websockify#204]
It'd be better to take command option to output logs to a file.

**Comment by DirectXMan12** [comment]
We already use the Python standard library's `logging` framework, so this should be as easy as adding a command line option for switching the logger to a file logger.

**Comment by jeffforbes** [comment]
I already made patches for  controlling the location of the log file and making sure all of the messages went to the same location and put them in a different issue report: https://github.com/kanaka/websockify/issues/193

I am not sure how to get them into the correct place for eventual incorporation into the code base.
