### ISSUE TITLE
--token-plugin error

### ISSUE THREAD

**Issue by khalilclaybon** [kanaka/websockify#213]
Hello, 
I am using websockify to bridge a connection from my spice virtual machine server to the spice html5 browser application. The parameters it takes are Host IP of the websockify server, Port websockify is listening on and a password. My target_list.config file looks like this .....

target1: 165.168.2.54:5908
target2: 165.168.2.54:5910
target3: 165.168.2.54:5909

when i run websockify as ./websockify.py --token-plugin TokenFile --token-source target_list.config  8080

and then try to connect via spice-html5 client, I get this response from websockify

10.0.0.2: Token not present

Is there something I am doing wrong ?

**Comment by DirectXMan12** [comment]
Did you fix your issue?

**Comment by zhangqunshi** [comment]
I got the same problem, why this issue closed?
BTW: i use the spice_auto.html, and change the token, it doesn't work. Also variable path is not used in spice_auto.html.

**Comment by DirectXMan12** [comment]
> why this issue closed?

The original submitter closed it.

You'll need to somehow pass the token as a query parameter in the websocket path (e.g. `wss://somehost:6080/websockify?token=mytoken`)

**Comment by srajan96** [comment]
Try opening the URL as below:
`http://localhost:6080/vnc.html?path=?token=token2`
This solved the issue for me.

Also, in case you get file not found error, try providing absolute path of the token source.

**Comment by SKJoy** [comment]
> Try opening the URL as below: `http://localhost:6080/vnc.html?path=?token=token2` This solved the issue for me.
> 
> Also, in case you get file not found error, try providing absolute path of the token source.

Take my thanks after 5 years man :) That URL argument separator, it is a `kIlLeR` ;)
