### ISSUE TITLE
Websockify Memcached Tokens

### ISSUE THREAD

**Issue by Ziris85** [kanaka/websockify#220]
Afternoon,

This isn't an issue so much as sharing how I got the token plugin working through memcached, in case someone else were looking to do the same. This example requires that you have `python-memcache` and `python-simplejson` installed on your system.

In this example, it assumes that the host information is part of a JSON array in memcached, and we will be fetching only the host information from that array for websockify to make its connection to. Add this to the `websockify/token_plugins.py` file:

```
import memcache
import simplejson

class TokenMemc(BasePlugin):
    def lookup(self, token):
        client = memcache.Client(['127.0.0.1:11211'], debug=0)
        stuff = client.get(token)
        combo = simplejson.loads(stuff)
        pair = combo["host"]
        return pair.split(':')
```
The above assumes that memcached is on the local machine, and that the IP and port of the remote machine are stored under the key name `host`. I'm sure this could probably be made simpler than what is above, but thought I might share with the community just in case.

**Comment by DirectXMan12** [comment]
Thanks for the sample!.  I'll drop it in a wiki page.
