### ISSUE TITLE
How to install websockify

### ISSUE THREAD

**Issue by doggdor** [kanaka/websockify#227]
Hello,

How I can install websockify for noVNC?

with: 
make
make install
I got the message: no rule to make target 'install'

**Comment by zhangqunshi** [comment]
You don't need install it, directly execute run.py script.

**Comment by dhumal436** [comment]
No installed websockify, attempting to clone websockify...
./utils/launch.sh: line 130: git: command not found
Unable to locate /home/shubham/novnc/utils/websockify/run after downloading

**Comment by totaam** [comment]
> git: command not found
Install git.
