### ISSUE TITLE
[Q] Using websockify to bridge wss:// to ws:// (TCP)

### ISSUE THREAD

**Issue by QuantumRevenger** [kanaka/websockify#232]
I have a linux box which runs a ws:// server (TCP) and my webclient wants to connect over wss:// (however, my server does not support this.)

How do I create a relay/bridge from wss:// to ws:// on the same machine?

E.g wss://relay-ip:101 to ws://local-ip:100

**Comment by kanaka** [comment]
WebSockets is standard SSL/TLS so you could probably use stunnel for this. Or probably any web service that supports transparent SSL front-end with non-SSL backend services. But this is out of scope for websockify.
