### ISSUE TITLE
websokify occured error(handler exception: need more than 1 value to unpack) ,what is wrong? who can help me 

### ISSUE THREAD

**Issue by zhangjianpinghik** [kanaka/websockify#235]
[root@localhost utils]# ./websockify/websockify.py --web=../ --target-config=vnc_tokens 6080
WARNING: no 'numpy' module, HyBi protocol will be slower
WebSocket server settings:
  - Listen on :6080
  - Flash security policy server
  - Web server. Web root: /root/noVNC
  - No SSL/TLS support (no cert file)
  - proxying from :6080 to targets generated by TokenFile
 
 handler exception: need more than 1 value to unpack

**Comment by zhangjianpinghik** [comment]
it is resolved ,my config file is wrong!

**Comment by steven-zou** [comment]
what's your config file? Could you share it to us?

**Comment by steven-zou** [comment]
there must be a space before the key: and value
