### ISSUE TITLE
one vnc client to multiple servers

### ISSUE THREAD

**Issue by Mutz2** [kanaka/websockify#241]
Hi at the backend i will have multiple vnc servers can it be shown on single html page using no vnc.

for example multiple mobile screens on one page for whose vnc server will be running at backend.

**Comment by DirectXMan12** [comment]
You could write a custom noVNC page that had multiple copies of noVNC embedded in it.  IIRC, there are a couple people that used noVNC like that.  However, this is not a websockify question, AFAICT.  If you need further guidance, please ask under https://github.com/kanaka/novnc
