### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by pan2za** [kanaka/websockify#256]
I hope to merge the following code,
Since in Windows, I can't tell how to make websockify to shutdown. I put some zeromq code inside to orchestrate with the shutdown action, that is, I make a configuration interface for websockify to receive some controlling command. You can find these code in my clone.
https://github.com/pan2za/websockify
Code sample:
def mq_listen(threadName, topic):
    
    print("mq_listen now")
    context = zmq.Context()
    
    # First, connect our subscriber socket
    subscriber = context.socket(zmq.SUB)
    subscriber.connect('tcp://172.16.17.240:16161')
    subscriber.setsockopt(zmq.SUBSCRIBE, "")

    while True:
        msg = subscriber.recv()
        print("mq recv mesg : "+msg)
        if msg == 'shutdown '+ str(topic):
            break
    print("zeromq listening end") 
    os._exit(1)

**Comment by samhed** [comment]
could you open a pull request instead please
