### ISSUE TITLE
websockify.exe: error: no such option: --multiprocessing-fork

### ISSUE THREAD

**Issue by puttys** [kanaka/websockify#28]
hi guys,
I am using windows xp ,followed the guide https://github.com/kanaka/websockify/wiki/Compiling-Websockify-as-Windows-Executable,the exe file has built,but there was always an error "websockify.exe: error: no such option: --multiprocessing-fork",I know nothing about the python,:(,but I have to use the websockify,could anbody send me an prebuilt version of websockify.exe.My email is hetianhe@gmail.com,thank you in advance.

**Comment by totaam** [comment]
Is there a solution for those that want to build from source rather than downloading a 4 year old zip file?
Tried with both python 2.7 and 3.4, both failed the same way.
(and that's after applying the fixes for SIGCHLD)

**Comment by n-elie** [comment]
Necro-bumping to let you know that multiprocessing freeze support needs to be called in `__main__.py` to solve this issue: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support
