### ISSUE TITLE
Missing documentation for parameter '--target-config'

### ISSUE THREAD

**Issue by dol** [kanaka/websockify#78]
The pull request #50 added the possibility to define a "--target-config", with I use in a project. I stumbled upon this parameter in the code. The target-config is quite useful to perform 'dynamic' TCP-to-Websocket mappings.
This applies also for noVNC.

**Comment by DirectXMan12** [comment]
closing due to no response

**Comment by kanaka** [comment]
BTW, this is now documented here: https://github.com/kanaka/websockify/wiki/Token-based-target-selection
